### ISSUE TITLE
TypeError: analyseCommand is not a function

### ISSUE THREAD

**Issue by sdgluck** [wpk-cli/wpk#15]
After a build I ran `wpk build analyse` and got this:

```
$ wpk build analyse
wpk build v0.0.4 beta
info webpack v4.27.1 (local)

err! an unknown error occurred
err! please report at github.com/wpk-cli/wpk/issues
err! error:

  TypeError: analyseCommand is not a function
      at Object.analyse (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@wpk-cli\command-build\dist\command.js:40:12)
      at C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@wpk-cli\command-build\dist\command.js:406:34
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
      at _next (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
      at C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
      at Promise._execute (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\bluebird\js\release\debuggability.js:313:9)
      at Promise._resolveFromExecutor (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\bluebird\js\release\promise.js:483:18)
      at new Promise (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\bluebird\js\release\promise.js:79:10)
      at C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
      at _wpkCommandBuild (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@wpk-cli\command-build\dist\command.js:458:30)
      at wpkCommandBuild (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@wpk-cli\command-build\dist\command.js:404:47)
      at C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\dist\command-run.js:98:22
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
      at _next (C:\nvm\v8.11.4\node_modules\@wpk-cli\cli\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
```

**Comment by sdgluck** [comment]
Fixed in 0.0.5
