### ISSUE TITLE
Sadly, I can't even run wpk init.

### ISSUE THREAD

**Issue by lukgreen** [wpk-cli/wpk#26]
> wpk init

    warn an error occurred trying to load commands
    warn run with --wpk-debug to see the error
    wpk init v0.0.6 beta
    info webpack v4.29.0 (local)
    warn live help disabled (console not tall enough)
    warn increase console height to at least 50 rows for live help

    Initialising new webpack configuration:
    ? Config filename: (webpack.config.js) /home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/cli/dist/util.js:154
      for (let i = 0; i < process.stdout.rows - cursor.row; i++) {
                                                   ^

    TypeError: Cannot read property 'row' of undefined
    at cleanConsole (/home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/cli/dist/util.js:154:52)
    at processError (/home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/cli/dist/util.js:142:3)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:448:27)

**Comment by sdgluck** [comment]
What OS and terminal are you using? Thanks for the issue.

**Comment by lukgreen** [comment]
The error persists although this time it doesn't give details and stacktrace differs:
```
Initialising new webpack configuration:
? Config filename: (webpack.config.js) 
err! an unknown error occurred
err! please report at github.com/wpk-cli/wpk/issues
err! error:

  TypeError: Cannot read property 'row' of undefined
      at Object.<anonymous> (/home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/prompt/dist/WpkPrompt.js:198:65)
      at WpkPrompt._runInquirer (/home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/prompt/dist/WpkPrompt.js:149:11)
      at /home/lukgreen/Documents/projects/wpk_test/node_modules/@wpk-cli/prompt/dist/WpkPrompt.js:516:31
      at Generator.next (<anonymous>)
```

The terminal is GNOME Terminal 3.28.2, OS is Ubuntu 18.04.

**Comment by sdgluck** [comment]
Thanks for that @lukgreen. That's the same problem but in a different place. It looks like the `get-cursor-position` dependency is not working on your machine. I will look into it further.

**Comment by sdgluck** [comment]
Posting this more so that I don't forget what I discovered.

After booting up a VM with Ubuntu 18.04 and playing around I've discovered that `getCursorPosition.sync()` doesn't work but `getCursorPosition.sync()` does.

As you can see from the images below with async it works, with sync it doesn't.

Sync (notice no cursor position object):
<img src="https://i.imgur.com/reIXiEn.png"/>

Async (notice cursor position object):
<img src="https://i.imgur.com/vbZjbQD.png"/>

**Comment by sdgluck** [comment]
@lukgreen 

If you install latest (v0.0.9) you can run `wpk init` with `--no-help`, and it should work ok for you (I tested it in my VM). Unfortunately this means you will not receive the live help and documentation for now.

With 0.0.9 the only command that should not work outright due to this bug will be `add plugin/loader`. I will continue looking into a fix for this. Thanks again for raising.

**Comment by sdgluck** [comment]
@lukgreen If you install latest (v0.0.9) you can use `wpk init --no-help` to run the command without live help and documentation.

The only command that shouldn't work outright for you on 0.0.9 is `wpk add plugin/loader`.

I'll continue looking into a fix for this. Thanks again for raising the issue.
